//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNCServices.CardCharging {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardCharging.CardChargingSoap")]
    public interface CardChargingSoap {
        
        // CODEGEN: Generating message contract since element name agentCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UseCard", ReplyAction="*")]
        CNCServices.CardCharging.UseCardResponse UseCard(CNCServices.CardCharging.UseCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UseCard", ReplyAction="*")]
        System.Threading.Tasks.Task<CNCServices.CardCharging.UseCardResponse> UseCardAsync(CNCServices.CardCharging.UseCardRequest request);
        
        // CODEGEN: Generating message contract since element name agentCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransaction", ReplyAction="*")]
        CNCServices.CardCharging.GetTransactionResponse GetTransaction(CNCServices.CardCharging.GetTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<CNCServices.CardCharging.GetTransactionResponse> GetTransactionAsync(CNCServices.CardCharging.GetTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UseCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UseCard", Namespace="http://tempuri.org/", Order=0)]
        public CNCServices.CardCharging.UseCardRequestBody Body;
        
        public UseCardRequest() {
        }
        
        public UseCardRequest(CNCServices.CardCharging.UseCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UseCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public UseCardRequestBody() {
        }
        
        public UseCardRequestBody(string agentCode, string data) {
            this.agentCode = agentCode;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UseCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UseCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public CNCServices.CardCharging.UseCardResponseBody Body;
        
        public UseCardResponse() {
        }
        
        public UseCardResponse(CNCServices.CardCharging.UseCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UseCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UseCardResult;
        
        public UseCardResponseBody() {
        }
        
        public UseCardResponseBody(string UseCardResult) {
            this.UseCardResult = UseCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransaction", Namespace="http://tempuri.org/", Order=0)]
        public CNCServices.CardCharging.GetTransactionRequestBody Body;
        
        public GetTransactionRequest() {
        }
        
        public GetTransactionRequest(CNCServices.CardCharging.GetTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public GetTransactionRequestBody() {
        }
        
        public GetTransactionRequestBody(string agentCode, string data) {
            this.agentCode = agentCode;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public CNCServices.CardCharging.GetTransactionResponseBody Body;
        
        public GetTransactionResponse() {
        }
        
        public GetTransactionResponse(CNCServices.CardCharging.GetTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTransactionResult;
        
        public GetTransactionResponseBody() {
        }
        
        public GetTransactionResponseBody(string GetTransactionResult) {
            this.GetTransactionResult = GetTransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardChargingSoapChannel : CNCServices.CardCharging.CardChargingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardChargingSoapClient : System.ServiceModel.ClientBase<CNCServices.CardCharging.CardChargingSoap>, CNCServices.CardCharging.CardChargingSoap {
        
        public CardChargingSoapClient() {
        }
        
        public CardChargingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardChargingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardChargingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardChargingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CNCServices.CardCharging.UseCardResponse CNCServices.CardCharging.CardChargingSoap.UseCard(CNCServices.CardCharging.UseCardRequest request) {
            return base.Channel.UseCard(request);
        }
        
        public string UseCard(string agentCode, string data) {
            CNCServices.CardCharging.UseCardRequest inValue = new CNCServices.CardCharging.UseCardRequest();
            inValue.Body = new CNCServices.CardCharging.UseCardRequestBody();
            inValue.Body.agentCode = agentCode;
            inValue.Body.data = data;
            CNCServices.CardCharging.UseCardResponse retVal = ((CNCServices.CardCharging.CardChargingSoap)(this)).UseCard(inValue);
            return retVal.Body.UseCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CNCServices.CardCharging.UseCardResponse> CNCServices.CardCharging.CardChargingSoap.UseCardAsync(CNCServices.CardCharging.UseCardRequest request) {
            return base.Channel.UseCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<CNCServices.CardCharging.UseCardResponse> UseCardAsync(string agentCode, string data) {
            CNCServices.CardCharging.UseCardRequest inValue = new CNCServices.CardCharging.UseCardRequest();
            inValue.Body = new CNCServices.CardCharging.UseCardRequestBody();
            inValue.Body.agentCode = agentCode;
            inValue.Body.data = data;
            return ((CNCServices.CardCharging.CardChargingSoap)(this)).UseCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CNCServices.CardCharging.GetTransactionResponse CNCServices.CardCharging.CardChargingSoap.GetTransaction(CNCServices.CardCharging.GetTransactionRequest request) {
            return base.Channel.GetTransaction(request);
        }
        
        public string GetTransaction(string agentCode, string data) {
            CNCServices.CardCharging.GetTransactionRequest inValue = new CNCServices.CardCharging.GetTransactionRequest();
            inValue.Body = new CNCServices.CardCharging.GetTransactionRequestBody();
            inValue.Body.agentCode = agentCode;
            inValue.Body.data = data;
            CNCServices.CardCharging.GetTransactionResponse retVal = ((CNCServices.CardCharging.CardChargingSoap)(this)).GetTransaction(inValue);
            return retVal.Body.GetTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CNCServices.CardCharging.GetTransactionResponse> CNCServices.CardCharging.CardChargingSoap.GetTransactionAsync(CNCServices.CardCharging.GetTransactionRequest request) {
            return base.Channel.GetTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CNCServices.CardCharging.GetTransactionResponse> GetTransactionAsync(string agentCode, string data) {
            CNCServices.CardCharging.GetTransactionRequest inValue = new CNCServices.CardCharging.GetTransactionRequest();
            inValue.Body = new CNCServices.CardCharging.GetTransactionRequestBody();
            inValue.Body.agentCode = agentCode;
            inValue.Body.data = data;
            return ((CNCServices.CardCharging.CardChargingSoap)(this)).GetTransactionAsync(inValue);
        }
    }
}
